// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/models/data/model_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 1939217860881988310),
      name: 'ModelEntity',
      lastPropertyId: const obx_int.IdUid(11, 2156050348572104246),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2587022995184791409),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7825512913007525001),
            name: 'modelId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4171116390053392350),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3190126099801450145),
            name: 'sizeBytes',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1419837066535701594),
            name: 'sizeLabel',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 3486866116011882684),
            name: 'statusIndex',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 907938986559373388),
            name: 'downloadProgress',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 3243296548773497384),
            name: 'localPath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 4464638976573896656),
            name: 'huggingFaceRepo',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 5212277854939496183),
            name: 'filename',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 2156050348572104246),
            name: 'format',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 1939217860881988310),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    ModelEntity: obx_int.EntityDefinition<ModelEntity>(
        model: _entities[0],
        toOneRelations: (ModelEntity object) => [],
        toManyRelations: (ModelEntity object) => {},
        getId: (ModelEntity object) => object.id,
        setId: (ModelEntity object, int id) {
          object.id = id;
        },
        objectToFB: (ModelEntity object, fb.Builder fbb) {
          final modelIdOffset = fbb.writeString(object.modelId);
          final nameOffset = fbb.writeString(object.name);
          final sizeLabelOffset = fbb.writeString(object.sizeLabel);
          final localPathOffset = object.localPath == null
              ? null
              : fbb.writeString(object.localPath!);
          final huggingFaceRepoOffset = object.huggingFaceRepo == null
              ? null
              : fbb.writeString(object.huggingFaceRepo!);
          final filenameOffset = object.filename == null
              ? null
              : fbb.writeString(object.filename!);
          final formatOffset = fbb.writeString(object.format);
          fbb.startTable(12);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, modelIdOffset);
          fbb.addOffset(2, nameOffset);
          fbb.addInt64(3, object.sizeBytes);
          fbb.addOffset(4, sizeLabelOffset);
          fbb.addInt64(5, object.statusIndex);
          fbb.addFloat64(6, object.downloadProgress);
          fbb.addOffset(7, localPathOffset);
          fbb.addOffset(8, huggingFaceRepoOffset);
          fbb.addOffset(9, filenameOffset);
          fbb.addOffset(10, formatOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = ModelEntity()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..modelId = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..sizeBytes =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0)
            ..sizeLabel = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 12, '')
            ..statusIndex =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0)
            ..downloadProgress =
                const fb.Float64Reader().vTableGet(buffer, rootOffset, 16, 0)
            ..localPath = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 18)
            ..huggingFaceRepo = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 20)
            ..filename = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 22)
            ..format = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 24, '');

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ModelEntity] entity fields to define ObjectBox queries.
class ModelEntity_ {
  /// See [ModelEntity.id].
  static final id =
      obx.QueryIntegerProperty<ModelEntity>(_entities[0].properties[0]);

  /// See [ModelEntity.modelId].
  static final modelId =
      obx.QueryStringProperty<ModelEntity>(_entities[0].properties[1]);

  /// See [ModelEntity.name].
  static final name =
      obx.QueryStringProperty<ModelEntity>(_entities[0].properties[2]);

  /// See [ModelEntity.sizeBytes].
  static final sizeBytes =
      obx.QueryIntegerProperty<ModelEntity>(_entities[0].properties[3]);

  /// See [ModelEntity.sizeLabel].
  static final sizeLabel =
      obx.QueryStringProperty<ModelEntity>(_entities[0].properties[4]);

  /// See [ModelEntity.statusIndex].
  static final statusIndex =
      obx.QueryIntegerProperty<ModelEntity>(_entities[0].properties[5]);

  /// See [ModelEntity.downloadProgress].
  static final downloadProgress =
      obx.QueryDoubleProperty<ModelEntity>(_entities[0].properties[6]);

  /// See [ModelEntity.localPath].
  static final localPath =
      obx.QueryStringProperty<ModelEntity>(_entities[0].properties[7]);

  /// See [ModelEntity.huggingFaceRepo].
  static final huggingFaceRepo =
      obx.QueryStringProperty<ModelEntity>(_entities[0].properties[8]);

  /// See [ModelEntity.filename].
  static final filename =
      obx.QueryStringProperty<ModelEntity>(_entities[0].properties[9]);

  /// See [ModelEntity.format].
  static final format =
      obx.QueryStringProperty<ModelEntity>(_entities[0].properties[10]);
}
